
# - name: "Copy {{component}} service"
#   ansible.builtin.copy:
#     src: "{{component}}.service"
#     dest: "/etc/systemd/system/{{component}}.service"

- name: "Copy {{component}} service"
  ansible.builtin.template:
    src: "{{component}}.service.j2"
    dest: "/etc/systemd/system/{{component}}.service"

- name: deamon realod and start
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Unmask the user service
  ansible.builtin.systemd:
    name: user
    masked: no

# - name: Enable and start the user service
#   ansible.builtin.systemd:
#     name: user
#     enabled: yes
#     state: started


- name: "start and enable {{component}}"
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted
    enabled: yes
